export type QuizQuestion = {
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
};

export type Lesson = {
  id: string;
  number: number;
  sourceFolder: string;
  title: string;
  minutes: number;
  summary: string;
  barrier: string;
  solution: string;
  takeaways: string[];
  challenge: string;
  quiz: QuizQuestion;
};

export type CourseModule = {
  id: number;
  title: string;
  goal: string;
  color: string;
  lessons: Lesson[];
};

export const courseModules: CourseModule[] = [
  {
    id: 1,
    title: 'Understanding Digital Accessibility',
    goal: 'Understand what accessibility is, why it matters, and the principles behind an accessible website.',
    color: '#ff5a00',
    lessons: [
      {
        id: 'digital-accessibility',
        number: 1,
        sourceFolder: '00',
        title: 'What Is Digital Accessibility?',
        minutes: 6,
        summary: 'Digital accessibility means designing websites, apps, and digital content so people with disabilities can use them independently and effectively.',
        barrier: 'A digital experience may technically load while still excluding someone who cannot see the screen, hear audio, use a mouse, or process a dense layout.',
        solution: 'Plan for different ways of seeing, hearing, moving, understanding, and communicating from the start—not as a repair at the end.',
        takeaways: ['Accessibility is about equal use, not a special version.', 'Disability can be permanent, temporary, or situational.', 'Accessible design often makes products easier for everyone.'],
        challenge: 'Choose one website you use often. Name one way a person could perceive it and one way they could operate it without relying on sight or a mouse.',
        quiz: {
          prompt: 'What is the main goal of digital accessibility?',
          options: ['Make every website look identical', 'Let people with different abilities use digital experiences', 'Remove all images and video', 'Create a separate website for every disability'],
          answer: 1,
          explanation: 'Accessibility supports many ways of perceiving, understanding, navigating, and interacting with the same experience.',
        },
      },
      {
        id: 'accessible-website',
        number: 2,
        sourceFolder: '08',
        title: 'What Makes a Website Accessible?',
        minutes: 7,
        summary: 'An accessible website presents information clearly and supports multiple input and output methods across content, structure, and interaction.',
        barrier: 'A page can look polished but fail when text is zoomed, a keyboard replaces the mouse, or a screen reader announces controls without useful names.',
        solution: 'Combine meaningful structure, readable presentation, keyboard access, clear feedback, and compatibility with assistive technology.',
        takeaways: ['Accessibility is a system, not a single feature.', 'Content, design, and code all contribute.', 'Real-user testing reveals barriers tools can miss.'],
        challenge: 'Open a familiar page and try three checks: zoom to 200%, press Tab five times, and identify whether every control still makes sense.',
        quiz: {
          prompt: 'Which approach best describes an accessible website?',
          options: ['One that passes only an automated scan', 'One with a large accessibility statement', 'One usable across different senses, inputs, and screen sizes', 'One that avoids interactive features'],
          answer: 2,
          explanation: 'Accessibility depends on the complete experience working across different ways people access and operate it.',
        },
      },
      {
        id: 'wcag',
        number: 3,
        sourceFolder: '02',
        title: 'What Is WCAG?',
        minutes: 7,
        summary: 'The Web Content Accessibility Guidelines are an international standard for making web content more perceivable, operable, understandable, and robust.',
        barrier: 'Without shared criteria, teams can use vague definitions of accessibility and overlook important barriers.',
        solution: 'Use WCAG success criteria as a testable baseline, then combine them with usability testing and feedback from disabled people.',
        takeaways: ['POUR stands for Perceivable, Operable, Understandable, and Robust.', 'WCAG has testable success criteria.', 'Conformance is a baseline, not the end of inclusive design.'],
        challenge: 'Take a feature on your site and place it under one POUR principle. Explain in one sentence what you would test.',
        quiz: {
          prompt: 'What does the “O” in WCAG’s POUR principles stand for?',
          options: ['Optional', 'Operable', 'Optimized', 'Observable'],
          answer: 1,
          explanation: 'Operable means people can navigate and use the interface with the input methods available to them.',
        },
      },
      {
        id: 'without-a-mouse',
        number: 4,
        sourceFolder: '16',
        title: 'Why Websites Need to Work Without a Mouse',
        minutes: 6,
        summary: 'People may use a keyboard, switch, voice commands, or other input instead of a mouse. Core actions must work without precise pointer movement.',
        barrier: 'Mouse-only menus, drag interactions, and controls that appear only on hover can block people with motor or vision disabilities.',
        solution: 'Make every interactive feature reachable and usable from the keyboard, preserve a logical order, and provide non-drag alternatives.',
        takeaways: ['Keyboard support helps several assistive technologies.', 'Hover cannot be the only way to reveal essential actions.', 'Logical focus order should match the task.'],
        challenge: 'Put your mouse aside for one minute. Tab through a page, activate a link with Enter, and activate a button with Space.',
        quiz: {
          prompt: 'Why is mouse-free operation essential?',
          options: ['Keyboards load pages faster', 'Some people use keyboards, switches, or voice instead of a pointer', 'It removes the need for visible buttons', 'WCAG prohibits all mouse use'],
          answer: 1,
          explanation: 'Supporting non-pointer input lets people use the interface with the technology and movement they have available.',
        },
      },
      {
        id: 'color-alone',
        number: 5,
        sourceFolder: '17',
        title: 'Why You Shouldn’t Use Color Alone to Communicate Information',
        minutes: 6,
        summary: 'Color is helpful reinforcement, but meaning should also be available through text, icons, patterns, or position.',
        barrier: 'A red field border or green status dot alone may be invisible or ambiguous to someone with color-vision differences or a monochrome display.',
        solution: 'Pair color with a persistent label, recognizable symbol, pattern, or written instruction that carries the same meaning.',
        takeaways: ['Color can reinforce meaning without carrying it alone.', 'Labels and icons make status easier to scan.', 'Check designs in grayscale to spot color-only cues.'],
        challenge: 'Find one success, warning, or error state. Add a non-color cue that communicates the same message.',
        quiz: {
          prompt: 'What is the best way to show a required-field error?',
          options: ['Use a red outline only', 'Make the field blink', 'Use a red outline plus an error icon and clear text', 'Reduce the field opacity'],
          answer: 2,
          explanation: 'The text and icon preserve the meaning even when the color difference is not perceived.',
        },
      },
    ],
  },
  {
    id: 2,
    title: 'Accessible Content',
    goal: 'Learn how everyday website content can create—or remove—barriers.',
    color: '#ccff00',
    lessons: [
      {
        id: 'alt-text',
        number: 6,
        sourceFolder: '03',
        title: 'What Is Alt Text?',
        minutes: 7,
        summary: 'Alternative text gives a concise, contextual description of an informative image to people who cannot see it.',
        barrier: 'Without useful alt text, a screen reader may announce only a file name—or skip information the image was meant to communicate.',
        solution: 'Describe the image’s purpose in context. Use empty alt text for decoration and avoid repeating nearby text.',
        takeaways: ['Context determines good alt text.', 'Be concise and describe what matters.', 'Decorative images usually need empty alt text.'],
        challenge: 'Write alt text for a photo of a crowded bus stop used in an article about unreliable transit. Focus on why the image is there.',
        quiz: {
          prompt: 'Which alt text is best for an informative chart?',
          options: ['chart.png', 'Image of a chart', 'Sales rose 25% from January to March', 'A very nice blue and white chart'],
          answer: 2,
          explanation: 'Good alt text communicates the information or purpose the image contributes in its context.',
        },
      },
      {
        id: 'captions',
        number: 7,
        sourceFolder: '07',
        title: 'Why Captions Matter',
        minutes: 6,
        summary: 'Captions provide synchronized text for speech and meaningful sounds so video is understandable without hearing the audio.',
        barrier: 'Dialogue-only or auto-generated captions can omit speaker changes, sound cues, names, and important words.',
        solution: 'Provide accurate, synchronized captions that identify speakers and include relevant non-speech audio.',
        takeaways: ['Captions include meaningful sounds, not only dialogue.', 'Accuracy and timing both matter.', 'Captions also help in noisy or quiet environments.'],
        challenge: 'Watch 30 seconds of a video with sound off. Note whether captions preserve the speaker, words, timing, and important sounds.',
        quiz: {
          prompt: 'What should quality captions include?',
          options: ['Only the loudest dialogue', 'Speech plus meaningful sounds and speaker changes', 'A summary shown before the video', 'Every visual detail on screen'],
          answer: 1,
          explanation: 'Synchronized captions should preserve the audio information needed to understand the video.',
        },
      },
      {
        id: 'color-contrast',
        number: 8,
        sourceFolder: '04',
        title: 'Why Color Contrast Matters',
        minutes: 7,
        summary: 'Strong contrast helps text and essential interface elements remain distinguishable for people with low vision or color-vision differences.',
        barrier: 'Light gray text, thin icons, and controls that blend into their background can become unreadable even when their size looks generous.',
        solution: 'Choose tested foreground/background pairs and check normal text, large text, focus indicators, icons, and control boundaries.',
        takeaways: ['Contrast is about the color pair, not one color.', 'Large text and normal text use different thresholds.', 'States and controls also need to remain visible.'],
        challenge: 'Use a contrast checker on one text/background pair from your site. Record the ratio and whether it passes for normal text.',
        quiz: {
          prompt: 'What determines text contrast?',
          options: ['The brightness of the text alone', 'The relationship between foreground and background colors', 'The font family only', 'Whether the text is centered'],
          answer: 1,
          explanation: 'Contrast is measured between the text color and the color directly behind it.',
        },
      },
      {
        id: 'heading-structure',
        number: 9,
        sourceFolder: '11',
        title: 'Why Heading Structure Matters',
        minutes: 6,
        summary: 'Headings create an outline that helps everyone scan a page and lets screen-reader users navigate directly between sections.',
        barrier: 'Text styled to look like a heading—but coded as a paragraph—does not appear in the page outline. Skipped levels can make relationships unclear.',
        solution: 'Use real heading elements in a logical hierarchy based on meaning, not on the visual size you want.',
        takeaways: ['Headings describe relationships between sections.', 'Use CSS for appearance and HTML for meaning.', 'A clear outline makes long pages easier to navigate.'],
        challenge: 'List the headings on one page without the body text. Does the outline still explain the page and its sections?',
        quiz: {
          prompt: 'How should you choose a heading level?',
          options: ['By the text size you want', 'By the section’s place in the page hierarchy', 'Use h1 for every bold phrase', 'Choose levels randomly for variety'],
          answer: 1,
          explanation: 'Heading levels communicate structure; their appearance can be styled separately with CSS.',
        },
      },
      {
        id: 'link-text',
        number: 10,
        sourceFolder: '13',
        title: 'Why Link Text Matters',
        minutes: 5,
        summary: 'Descriptive link text tells people where a link goes or what it does, including when links are read out of surrounding context.',
        barrier: 'A list of “click here” or “read more” links gives screen-reader and voice-control users little information for choosing the right one.',
        solution: 'Put the destination or action in the link itself: “Download the accessibility checklist” is clearer than “Click here.”',
        takeaways: ['Link purpose should be clear from its text.', 'Avoid visible raw URLs when a meaningful label works.', 'Unique link names improve voice and screen-reader navigation.'],
        challenge: 'Rewrite this link: “To see our accessibility guide, click here.” Make the linked words meaningful on their own.',
        quiz: {
          prompt: 'Which link text is most useful on its own?',
          options: ['Click here', 'Learn more', 'Download the event accessibility checklist', 'This page'],
          answer: 2,
          explanation: 'It clearly identifies both the action and the destination without relying on surrounding text.',
        },
      },
    ],
  },
  {
    id: 3,
    title: 'Accessible Interaction',
    goal: 'Understand how people navigate and operate accessible interfaces.',
    color: '#77e4ff',
    lessons: [
      {
        id: 'keyboard-navigation',
        number: 11,
        sourceFolder: '05',
        title: 'What Is Keyboard Navigation?',
        minutes: 7,
        summary: 'Keyboard navigation lets people move through and operate a page using keys such as Tab, Shift+Tab, Enter, Space, and the arrow keys.',
        barrier: 'Custom controls can look clickable but never receive keyboard focus, or they may respond only to mouse clicks.',
        solution: 'Start with native interactive elements, preserve a logical focus order, and test every action without touching the mouse.',
        takeaways: ['Tab and Shift+Tab move through interactive elements.', 'Enter and Space activate different native controls.', 'Native HTML provides expected behavior by default.'],
        challenge: 'Complete one real task using only the keyboard. Write down the first place where focus or operation becomes unclear.',
        quiz: {
          prompt: 'What is the most useful first keyboard test?',
          options: ['Press Tab through every interactive control', 'Type random letters', 'Turn off the monitor', 'Change the browser theme'],
          answer: 0,
          explanation: 'Tabbing exposes unreachable controls, confusing order, and missing focus indicators quickly.',
        },
      },
      {
        id: 'focus-indicator',
        number: 12,
        sourceFolder: '10',
        title: 'What Is a Focus Indicator?',
        minutes: 6,
        summary: 'A focus indicator is the visible outline or styling that shows which interactive element will respond to keyboard input.',
        barrier: 'Removing outlines without a replacement leaves keyboard users unsure where they are on the page.',
        solution: 'Provide a high-contrast, clearly visible focus style that is not clipped or hidden by nearby content.',
        takeaways: ['Focus is the keyboard equivalent of pointer location.', 'Never remove outlines without a strong replacement.', 'Focus and hover are different states.'],
        challenge: 'Tab through five controls. Can you identify focus instantly without reading the label or moving the mouse?',
        quiz: {
          prompt: 'What does a focus indicator communicate?',
          options: ['Which element is currently selected for keyboard interaction', 'Which page loaded fastest', 'Which link was visited yesterday', 'Whether the mouse is connected'],
          answer: 0,
          explanation: 'The indicator makes the current keyboard position visible.',
        },
      },
      {
        id: 'accessible-button',
        number: 13,
        sourceFolder: '12',
        title: 'What Makes a Button Accessible?',
        minutes: 7,
        summary: 'An accessible button has the right semantic element, a clear name, visible states, and reliable keyboard and touch behavior.',
        barrier: 'A clickable div may not receive focus, announce itself as a button, or activate with the expected keys.',
        solution: 'Use a native button, give it an action-oriented label, show focus and disabled states, and keep the target comfortably sized.',
        takeaways: ['Use the button element for actions.', 'A button needs a clear accessible name.', 'States should be visible and programmatically available.'],
        challenge: 'Inspect one icon-only button. Write the accessible name a screen reader should announce.',
        quiz: {
          prompt: 'What is the strongest starting point for an action control?',
          options: ['A styled div with a click event', 'A native button with a clear label', 'An image with no alt text', 'A colored span'],
          answer: 1,
          explanation: 'Native buttons include semantics, focusability, and expected keyboard behavior.',
        },
      },
      {
        id: 'accessible-form',
        number: 14,
        sourceFolder: '09',
        title: 'What Makes a Form Accessible?',
        minutes: 8,
        summary: 'Accessible forms connect every field to a clear label, group related choices, explain requirements, and provide understandable feedback.',
        barrier: 'Placeholder-only labels disappear as people type and may not be announced consistently. Ambiguous required fields create avoidable errors.',
        solution: 'Use persistent labels and instructions, semantic groups, sensible autocomplete, and errors tied directly to the affected field.',
        takeaways: ['Every control needs a persistent label.', 'Explain format and requirements before submission.', 'Connect help and errors to the relevant field.'],
        challenge: 'Review one form field. Check its label, required status, expected format, autocomplete purpose, and error message.',
        quiz: {
          prompt: 'Why is placeholder text not a reliable replacement for a label?',
          options: ['It is always too colorful', 'It disappears during input and may not identify the field clearly', 'It prevents keyboard input', 'It makes forms load slowly'],
          answer: 1,
          explanation: 'People need a persistent, programmatically connected label before, during, and after entering data.',
        },
      },
      {
        id: 'error-messages',
        number: 15,
        sourceFolder: '20',
        title: 'Why Error Messages Matter',
        minutes: 6,
        summary: 'Good error messages identify what went wrong, where it happened, and how to correct it without relying on color alone.',
        barrier: '“Something went wrong” gives no recovery path. Moving focus unpredictably or clearing entered data makes errors harder to fix.',
        solution: 'Keep user input, summarize errors when helpful, link messages to fields, and give specific correction guidance.',
        takeaways: ['Name the problem and the fix.', 'Keep valid user input whenever possible.', 'Make errors easy to find with focus and programmatic connections.'],
        challenge: 'Rewrite “Invalid input” for a date field that requires MM/DD/YYYY. Include both the problem and the expected format.',
        quiz: {
          prompt: 'Which error message is most actionable?',
          options: ['Invalid', 'Something went wrong', 'Enter the date as MM/DD/YYYY, for example 09/14/2026', 'Red field'],
          answer: 2,
          explanation: 'It identifies the expected correction and provides a concrete example.',
        },
      },
    ],
  },
  {
    id: 4,
    title: 'Building Accessible Websites',
    goal: 'Move from awareness to practical implementation with structure, names, and robust components.',
    color: '#ff8baa',
    lessons: [
      {
        id: 'semantic-html',
        number: 16,
        sourceFolder: '14',
        title: 'What Is Semantic HTML?',
        minutes: 7,
        summary: 'Semantic HTML uses elements whose built-in meaning describes the content or control, such as nav, main, button, and table.',
        barrier: 'Generic containers do not automatically tell browsers or assistive technology what a region or control is meant to do.',
        solution: 'Choose native elements by meaning first, then style them. Add custom behavior only when no native pattern fits.',
        takeaways: ['Semantics communicate purpose to software.', 'Native elements include useful behavior.', 'Choose tags for meaning, not appearance.'],
        challenge: 'Find three generic divs in a page concept. Decide whether header, nav, main, section, button, or another semantic element fits better.',
        quiz: {
          prompt: 'Why prefer semantic HTML?',
          options: ['It always uses fewer colors', 'It communicates meaning and often includes accessible behavior', 'It eliminates the need for CSS', 'It works only on mobile'],
          answer: 1,
          explanation: 'Semantic elements expose structure, roles, and expected behavior to browsers and assistive technology.',
        },
      },
      {
        id: 'accessible-name',
        number: 17,
        sourceFolder: '06',
        title: 'What Is an Accessible Name?',
        minutes: 7,
        summary: 'An accessible name is the label assistive technology uses to identify a control, link, landmark, or other element.',
        barrier: 'An icon-only control without a name may be announced only as “button,” leaving its action unknown.',
        solution: 'Use visible text when possible; otherwise provide a concise programmatic label that matches the visible action and avoids duplication.',
        takeaways: ['Accessible names identify controls.', 'Visible labels are usually the strongest source.', 'Names should be unique enough for the context.'],
        challenge: 'List the names you expect a screen reader to announce for your page’s search, menu, close, and submit controls.',
        quiz: {
          prompt: 'What should an accessible name answer?',
          options: ['What color is this?', 'What is this control or what does it do?', 'Who wrote the CSS?', 'How many pixels wide is it?'],
          answer: 1,
          explanation: 'The name identifies the element or its action so a person can choose and operate it.',
        },
      },
      {
        id: 'aria',
        number: 18,
        sourceFolder: '15',
        title: 'What Is ARIA?',
        minutes: 8,
        summary: 'ARIA adds roles, states, and relationships to help assistive technology understand interfaces when native HTML alone cannot express the pattern.',
        barrier: 'Incorrect ARIA can override useful native semantics or announce a state that does not match what the interface actually does.',
        solution: 'Use native HTML first. Add only the ARIA a tested custom pattern requires, and update dynamic states in sync with the interface.',
        takeaways: ['Native HTML comes first.', 'ARIA changes meaning, not behavior.', 'Dynamic states must stay accurate.'],
        challenge: 'Choose a custom disclosure. Name the native element you could use, or the ARIA state that must change when it opens.',
        quiz: {
          prompt: 'Which statement about ARIA is correct?',
          options: ['ARIA automatically adds keyboard behavior', 'ARIA should replace all native HTML', 'ARIA can describe roles and states but developers must implement behavior', 'ARIA is only for visual styling'],
          answer: 2,
          explanation: 'ARIA affects what assistive technology understands; it does not create interaction behavior by itself.',
        },
      },
      {
        id: 'skip-link',
        number: 19,
        sourceFolder: '22',
        title: 'What Is a Skip Link?',
        minutes: 5,
        summary: 'A skip link is an early keyboard link that moves focus past repeated navigation to the page’s main content.',
        barrier: 'Keyboard and screen-reader users may otherwise repeat dozens of navigation stops every time a page loads.',
        solution: 'Place a “Skip to main content” link first in the focus order and make its target focusable and reliable.',
        takeaways: ['Skip links reduce repeated navigation.', 'They should become visible on focus.', 'The destination should be the main content region.'],
        challenge: 'Press Tab immediately after a page loads. If there is a skip link, use it and confirm focus lands at the main content.',
        quiz: {
          prompt: 'Where should a skip link appear in keyboard order?',
          options: ['Near the end of the footer', 'As one of the first focusable elements', 'Only inside a settings dialog', 'After every paragraph'],
          answer: 1,
          explanation: 'It must be available before repeated navigation so users can bypass it efficiently.',
        },
      },
      {
        id: 'accessible-table',
        number: 20,
        sourceFolder: '21',
        title: 'What Makes a Table Accessible?',
        minutes: 7,
        summary: 'An accessible data table identifies its headers and relationships so people can understand what each cell means as they move through it.',
        barrier: 'Visual alignment alone does not preserve row and column context for a screen reader navigating cell by cell.',
        solution: 'Use tables for data, add a concise caption when useful, mark header cells with th, and define scope for rows or columns.',
        takeaways: ['Use tables for data, not page layout.', 'Headers give cells context.', 'Keep complex tables as simple as the information allows.'],
        challenge: 'Read one data cell without looking at its row or column. Write the two headers someone needs to understand its value.',
        quiz: {
          prompt: 'What gives a data cell its essential context?',
          options: ['A decorative background', 'Its associated row and column headers', 'The page footer', 'A larger font size'],
          answer: 1,
          explanation: 'Proper header relationships let assistive technology announce what each data value represents.',
        },
      },
    ],
  },
  {
    id: 5,
    title: 'Responsive & Usable Accessibility',
    goal: 'Support zoom, small screens, different motor abilities, and varied ways of navigating.',
    color: '#ffd45a',
    lessons: [
      {
        id: 'reflow',
        number: 21,
        sourceFolder: '18',
        title: 'What Is Reflow?',
        minutes: 6,
        summary: 'Reflow lets content adapt to a narrow viewport or high zoom without forcing two-dimensional scrolling for ordinary reading and operation.',
        barrier: 'Fixed-width layouts can push text and controls off screen, forcing people using zoom to pan left and right for every line.',
        solution: 'Use responsive layouts, flexible sizing, wrapping text, and intentional exceptions only when two-dimensional content truly requires them.',
        takeaways: ['Reflow reduces horizontal panning.', 'Responsive design supports both small screens and zoom.', 'Test content, controls, dialogs, and navigation.'],
        challenge: 'Set a browser window to a narrow width and zoom in. Find one element that clips, overlaps, or causes horizontal scrolling.',
        quiz: {
          prompt: 'What problem does reflow primarily reduce?',
          options: ['The need to scroll in two directions to read ordinary content', 'The number of headings', 'The need for captions', 'The size of downloaded images'],
          answer: 0,
          explanation: 'Reflow rearranges content into a usable single-column or wrapped layout at narrow widths and high zoom.',
        },
      },
      {
        id: 'text-resizing',
        number: 22,
        sourceFolder: '19',
        title: 'Why Text Resizing Matters',
        minutes: 6,
        summary: 'People enlarge text to read comfortably. The page should preserve content and functionality when text size increases substantially.',
        barrier: 'Fixed heights and tiny containers can clip enlarged text, cover controls, or make instructions disappear.',
        solution: 'Use flexible dimensions, allow wrapping, avoid image-only text, and test text enlargement separately from full-page zoom.',
        takeaways: ['Text enlargement is different from browser zoom.', 'Containers need room to grow.', 'No information or action should disappear.'],
        challenge: 'Increase browser text size to 200%. Check navigation, buttons, form labels, and cards for clipping or overlap.',
        quiz: {
          prompt: 'Which CSS choice best supports text resizing?',
          options: ['Fixed-height text boxes', 'Flexible containers that can grow and wrap', 'Text embedded only in images', 'Hidden overflow on every card'],
          answer: 1,
          explanation: 'Flexible containers adapt when text becomes larger or wraps onto more lines.',
        },
      },
      {
        id: 'button-size',
        number: 23,
        sourceFolder: '24',
        title: 'Why Button Size Matters',
        minutes: 6,
        summary: 'Comfortable target size and spacing help people with limited dexterity, tremors, low vision, or touch input activate the intended control.',
        barrier: 'Tiny icons packed close together increase accidental activation and make controls hard to find or reach.',
        solution: 'Give controls a generous hit area, enough separation, a clear label, and adequate contrast in every state.',
        takeaways: ['The hit area can be larger than the visible icon.', 'Spacing reduces accidental activation.', 'Touch, mouse, and motor needs overlap.'],
        challenge: 'Use one hand and your non-dominant thumb to activate three controls. Note which target requires excessive precision.',
        quiz: {
          prompt: 'Why can increasing a button’s hit area help?',
          options: ['It guarantees faster internet', 'It reduces the precision needed to activate the control', 'It removes the need for a label', 'It makes focus indicators unnecessary'],
          answer: 1,
          explanation: 'A generous target is easier to acquire with touch, a pointer, or limited motor precision.',
        },
      },
      {
        id: 'keyboard-trap',
        number: 24,
        sourceFolder: '23',
        title: 'What Is a Keyboard Trap?',
        minutes: 6,
        summary: 'A keyboard trap occurs when focus enters a component and the user cannot move out using the keyboard.',
        barrier: 'Menus, embedded media, and dialogs can capture focus, leaving a keyboard user unable to continue or return to the page.',
        solution: 'Provide a standard exit, keep focus intentionally contained only while necessary, and return focus to a logical place when the component closes.',
        takeaways: ['Every keyboard path needs an exit.', 'Modal focus containment is temporary and intentional.', 'Escape behavior should match user expectations.'],
        challenge: 'Open a menu or dialog using the keyboard. Confirm Tab stays logical, Escape closes when expected, and focus returns to the trigger.',
        quiz: {
          prompt: 'What defines a keyboard trap?',
          options: ['A page with many links', 'Focus enters an area and cannot leave by keyboard', 'A visible focus outline', 'A shortcut that uses two keys'],
          answer: 1,
          explanation: 'The critical problem is losing the ability to move focus out and continue the task.',
        },
      },
      {
        id: 'screen-magnification',
        number: 25,
        sourceFolder: '29',
        title: 'Screen Magnification',
        minutes: 7,
        summary: 'Screen magnification enlarges part or all of the display for people with low vision, making layout stability and nearby feedback especially important.',
        barrier: 'At high magnification, only a small portion of the page is visible. Distant errors, unexpected movement, and sticky overlays can hide the task.',
        solution: 'Keep related labels and feedback close, support reflow, move focus intentionally, and avoid unnecessary layout shifts.',
        takeaways: ['Magnification reduces the visible context.', 'Nearby labels and errors lower search effort.', 'Stable layouts and clear focus movement matter.'],
        challenge: 'Zoom to 400% and complete a short form. Count how often you must pan to connect a control with its label or feedback.',
        quiz: {
          prompt: 'Why should an error message appear near its field?',
          options: ['To use more screen space', 'Magnification may hide distant context from view', 'To prevent text resizing', 'To make the page scroll faster'],
          answer: 1,
          explanation: 'At high magnification, nearby information is much easier to locate and connect with the control.',
        },
      },
    ],
  },
  {
    id: 6,
    title: 'Assistive Technology',
    goal: 'See how people use the accessible features you have learned to design and build.',
    color: '#b79cff',
    lessons: [
      {
        id: 'screen-reader',
        number: 26,
        sourceFolder: '01',
        title: 'What Is a Screen Reader?',
        minutes: 7,
        summary: 'A screen reader converts on-screen information into synthesized speech or braille and provides commands for navigating structure and controls.',
        barrier: 'Visual appearance alone does not expose meaning. Unlabeled controls and missing structure can turn a clear screen into a confusing stream of words.',
        solution: 'Use semantic structure, clear names, logical order, meaningful alternatives, and status updates that assistive technology can detect.',
        takeaways: ['Screen readers expose structure, names, roles, and states.', 'Users often navigate by headings, links, or landmarks.', 'Visual and programmatic experiences should stay aligned.'],
        challenge: 'Use a screen reader or page accessibility tree to list the first five interactive elements and how each is announced.',
        quiz: {
          prompt: 'How does a screen reader commonly present information?',
          options: ['Only by enlarging pixels', 'Through synthesized speech or refreshable braille', 'By changing every color to black', 'Only through printed output'],
          answer: 1,
          explanation: 'Screen readers interpret programmatic information and present it as speech or braille.',
        },
      },
      {
        id: 'aac',
        number: 27,
        sourceFolder: '25',
        title: 'What Is AAC?',
        minutes: 6,
        summary: 'Augmentative and Alternative Communication includes tools and methods that support or replace speech, from symbol boards to speech-generating devices.',
        barrier: 'Time limits, speech-only support, and complex language can prevent AAC users from expressing choices or completing interactions.',
        solution: 'Allow enough time, support multiple communication methods, use plain language, and avoid assuming speech reflects understanding.',
        takeaways: ['AAC includes low-tech and high-tech methods.', 'Communication may take more time.', 'Offer choices without limiting a person’s voice.'],
        challenge: 'Rewrite one rushed, open-ended prompt as a clear question with meaningful choices and enough time to respond.',
        quiz: {
          prompt: 'What is AAC designed to support?',
          options: ['Only website animation', 'Communication that augments or replaces speech', 'Color calibration', 'Faster page downloads'],
          answer: 1,
          explanation: 'AAC covers a wide range of tools and strategies people use to communicate.',
        },
      },
      {
        id: 'braille-display',
        number: 28,
        sourceFolder: '26',
        title: 'What Is a Refreshable Braille Display?',
        minutes: 6,
        summary: 'A refreshable braille display raises and lowers pins to present a changing line of digital text that can be read by touch.',
        barrier: 'Poor labels, unusual symbols, and flattened image text provide little useful information to the screen reader feeding the braille display.',
        solution: 'Provide concise text alternatives, semantic structure, predictable control names, and text-based content that can be programmatically accessed.',
        takeaways: ['The display presents changing digital braille.', 'It commonly works with screen-reader software.', 'Clear structure and concise names improve navigation.'],
        challenge: 'Reduce a long button label to the shortest wording that preserves its unique action when read one line at a time.',
        quiz: {
          prompt: 'What does a refreshable braille display do?',
          options: ['Prints permanent paper pages', 'Uses moving pins to present changing digital text', 'Adds captions to video', 'Controls a mouse pointer with eye movement'],
          answer: 1,
          explanation: 'Its cells update dynamically so a person can read digital information by touch.',
        },
      },
      {
        id: 'voice-control',
        number: 29,
        sourceFolder: '27',
        title: 'What Is Voice Control?',
        minutes: 6,
        summary: 'Voice control lets people navigate and operate a device with spoken commands, often by saying visible labels or numbered overlays.',
        barrier: 'When a control’s visible label differs from its accessible name, commands such as “Click Search” may fail.',
        solution: 'Keep accessible names aligned with visible text, use unique labels, support standard controls, and avoid interactions that depend on dragging alone.',
        takeaways: ['Visible labels should appear in accessible names.', 'Unique action labels are easier to target.', 'Standard controls work with common voice commands.'],
        challenge: 'Compare three visible control labels with their accessible names. Rewrite any name that does not contain the words a user can see and say.',
        quiz: {
          prompt: 'Why should a control’s accessible name match its visible label?',
          options: ['So the background changes color', 'So voice users can target it using the words they see', 'So the page has fewer headings', 'So captions play automatically'],
          answer: 1,
          explanation: 'Matching labels make spoken commands predictable and reduce confusion for all users.',
        },
      },
      {
        id: 'switch-access',
        number: 30,
        sourceFolder: '28',
        title: 'What Is Switch Access?',
        minutes: 7,
        summary: 'Switch access lets people operate a device with one or more switches while software moves—or scans—through available choices.',
        barrier: 'A long, illogical focus order, tiny targets, and mouse-only controls can make a short task exhausting or impossible with switch scanning.',
        solution: 'Keep navigation efficient and predictable, use semantic controls, group actions logically, and remove unnecessary focus stops.',
        takeaways: ['Scanning moves through choices in sequence.', 'Every extra focus stop adds effort.', 'Keyboard-accessible, semantic controls support switch access.'],
        challenge: 'Count the focus stops needed to complete one task. Identify two stops you could remove, combine, or move to shorten the path.',
        quiz: {
          prompt: 'What most directly improves a switch-scanning experience?',
          options: ['More decorative animation', 'A logical order with fewer unnecessary focus stops', 'Mouse-only hover menus', 'Longer button labels'],
          answer: 1,
          explanation: 'Efficient, predictable focus order reduces the number of scans and actions needed to complete a task.',
        },
      },
    ],
  },
];

export const allLessons = courseModules.flatMap((module) => module.lessons);

export const finalQuestionLessonIds = [
  'digital-accessibility',
  'wcag',
  'color-alone',
  'alt-text',
  'heading-structure',
  'keyboard-navigation',
  'accessible-form',
  'semantic-html',
  'aria',
  'accessible-table',
  'reflow',
  'keyboard-trap',
  'screen-reader',
  'voice-control',
  'switch-access',
];
